<a href="https://colab.research.google.com/github/volkov-maxim/nn_cv_course_samsung_stepik/blob/main/2_7_Realize_grad_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor([[1., 2., 3., 4.,],
                  [5., 6., 7., 8.,],
                  [9., 10., 11., 12]], requires_grad=True)

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [4]:
x = x.to(device)

In [5]:
function = 10 * (x ** 2).sum()

In [6]:
function.backward()

In [7]:
print(f"Gradient: {x.grad}")

Gradient: tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]])


In [12]:
x, function

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]], requires_grad=True),
 tensor(0.5463, grad_fn=<ProdBackward0>))

In [13]:
x.data

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [14]:
x.data -= 0.001 * x.grad

In [15]:
x.data

tensor([[ 0.9800,  1.9600,  2.9400,  3.9200],
        [ 4.9000,  5.8800,  6.8600,  7.8400],
        [ 8.8200,  9.8000, 10.7800, 11.7600]])

In [16]:
x.grad

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]])

In [17]:
x.grad.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
x.grad

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
w = torch.tensor([[5., 10.],
                  [1., 2.]], requires_grad=True)

In [37]:
alpha = 0.001
optimizer = torch.optim.SGD([w], lr=alpha)

In [38]:
for _ in range(500):
  function = (w+7).log().log().prod()
  function.backward()
  #w.data -= alpha * w.grad
  #w.grad.zero_()
  optimizer.step()
  optimizer.zero_grad()

In [39]:
w.data

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]])